import Head from 'next/head';
import { useContext } from 'react';
import { TaskContext } from '../context';
import styles from '../styles/Home.module.css';

export default function Home() {
   
  const { hello } = useContext(TaskContext);

  console.log(hello)
  return (
    <div >
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{hello}</h1>
      <h2>{hello}</h2>

    </div>
  )
}
