import Head from 'next/head';
import Layout from '../components/Layout';
import { useTask } from '../context';
import styles from '../styles/Home.module.css';

export default function Home() {  
  const {task} = useTask();

  console.log(task)

  return (
    <div >
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1>Hola mundo</h1>
      </Layout>

    </div>
  )
}
